# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: '0 0 * * *'
  displayName: 'Daily WS1 Intelligence Report'
  branches:
    include:
    - np
  always: true

variables:
  resourceGroupName: 'az-np-westus2-usr-624-Client_HW_Int-netstructures'
  storageAccountName: 'awnpstorageacct'
  containerName: 'intelstoragecontainer'
  macosapps_id: 'acafaef3-8af6-405c-bc91-84c59d2a69d5'
  macosapps_filePath: '/home/vsts/work/_temp/macapps_report.csv'

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Generate report for MacOS apps.'
  inputs:
    arguments: > #
      -report $(macosapps_id)
      -filePath $(macosapps_filePath)
    filePath: 'generate_report.ps1'

# WORKAROUND
#- task: AzurePowerShell@5
#  displayName: 'Upload MacOS apps report to Azure Blob Storage.'
#  inputs:
#    azureSubscription: 'az-np-usr-624-client_hw_int-arm-service-endpoint'
#    ScriptType: 'FilePath'
#    ScriptPath: 'upload.ps1'
#    ScriptArguments: '-resourceGroupName $(resourceGroupName) -storageAccountName $(storageAccountName) -containerName $(containerName) -filePath $(macosapps_filePath)'
#    azurePowerShellVersion: 'LatestVersion'
    
- script: |
    terraform --version
    terraform init -input=false
  displayName: 'Initialize Terraform configs.'

- script: terraform import azurerm_resource_group.rg "/subscriptions/eed2b1dd-900b-446f-9150-007ffb679353/resourceGroups/PBI2ADLS"
  timeoutInMinutes: 1
  displayName: 'Import AZ resource group.'

- script: terraform import azurerm_storage_account.storageacc "/subscriptions/eed2b1dd-900b-446f-9150-007ffb679353/resourceGroups/PBI2ADLS/providers/Microsoft.Storage/storageAccounts/pbi2adlsstorage"
  timeoutInMinutes: 1
  displayName: 'Import AZ storage account.'

- script: terraform import azurerm_storage_container.storagecontainer "https://pbi2adlsstorage.blob.core.windows.net/ws1intel"
  timeoutInMinutes: 1
  displayName: 'Import AZ storage container.'

- script: terraform import azurerm_storage_blob.storagefile "https://pbi2adlsstorage.blob.core.windows.net/ws1intel/ws1intelreport.csv"
  timeoutInMinutes: 1
  displayName: 'Import AZ storage blob.'

- script: terraform plan -out=tfplan -input=false
  displayName: 'Create Terraform plan and save to tfplan.'

- script: terraform apply -refresh-only -input=false tfplan
  displayName: 'Apply Terraform configs.'
  condition: succeeded()

- script: terraform state list
  displayName: 'Show Terraform state.'
